package constant

const (
	OK                         = "OK"
	SUCCESS                    = "success"
	FAILED                     = "failed"
	DUPLICATE_NIP              = "NIP already registered"
	SUCCESS_REGISTER_USER      = "user registered successfully"
	SUCCESS_UPDATE_USER        = "user updated successfully"
	USER_NOT_FOUND             = "user not found"
	SUCCESS_LOGIN              = "successfully logged in"
	FAILED_LOGIN               = "failed login, password is wrong"
	FAILED_GET_USERS           = "failed to get list of users"
	INVALID_NIP                = "invalid NIP"
	INVALID_TOKEN              = "invalid token"
	INVALID_SIGNING_METHOD     = "invalid token signing method"
	INVALID_TOKEN_CLAIMS       = "invalid token claims"
	TOKEN_EXPIRED              = "token already expired"
	DUPLICATE_IDENTITY_NUMBER  = "identity number already registered"
	SUCCESS_ADD_PATIENT        = "patient added successfully"
	PATIENT_NOT_FOUND          = "patient not found"
	FAILED_GET_PATIENTS        = "failed to get list of patients"
	FAILED_GET_MEDICAL_RECORDS = "failed to get list of medical records"
	SUCCESS_UPLOAD_FILE        = "file uploaded successfully"
)
